---
# tasks file for nginx_php
- name: Ensure nginx and php-fpm is installed.
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  loop:
    - nginx
    - php-common
    - php7.4-cli
    - php7.4-common
    - php7.4-fpm
    - php7.4-json
    - php7.4-opcache
    - php7.4-readline
    -
- name: Ensure service is running
  ansible.builtin.service:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    - nginx
    - php7.4-fpm

- name: Copy nginx config
  copy:
    src: default
    dest: /etc/nginx/sites-available
    mode: '0644'
  notify:
    - reload nginx

- name: Copy index.php to default locatin
  copy:
    src: index.php
    dest: /var/www/html/
    owner: www-data
    group: www-data
    mode: '0644'
  notify:
    - reload nginx

############## #4 ADDON TO P.3 ####################
- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /opt/nginx/ansible/
    state: directory
    mode: '0755'
    owner: www-data
    group: www-data
- name: Copy index.php to new locatin

  copy:
    src: index.php
    dest: /opt/nginx/ansible/
    owner: www-data
    group: www-data
    mode: '0644'

- name: Chenge document root folder
  ansible.builtin.lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '^[ \t\n]*root (.*);$'
    line: '\troot /opt/nginx/ansible;'
    backrefs: yes
  notify:
    - reload nginx